ontology/app1/urls.py
from django.contrib import admin
from django.urls import path, include
from app1.views import *


urlpatterns = [
    path('', IndexPage.as_view()),
    path('creationenviroment/', OntologyCreationEnvironment.as_view()),
    path('posthandler/', PostHandler.as_view()), #Обработчик post запросов на изменение триплетов от creationenviroment
    path('getsrtuctureontology/', GetStructureOntology.as_view()) #Получение структуры классов и подклассов в json creationenviroment
]

ontology/ontology/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ontology/', include('app1.urls')),
]

ontology/app1/models.py
from django.db import models

from django.dispatch import receiver
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db.models.signals import post_save

# Create your models here.
class CreatedOntology(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, unique=False, db_column='author')
    name = models.CharField(max_length=100, unique=True, blank=False, db_column='name') #Название онтологии
    description = models.TextField(max_length=1000, blank=True, db_column='description') #Описание онтологии

    data = models.DateTimeField(db_column='data') #Дата создания онтологии

    def __str__(self):
        return "ontology:{}".format(self.name)

class Triplets(models.Model): #Список триплетов в онтологии
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,db_column='author') #Автор ограничения
    ontology = models.ForeignKey(CreatedOntology, on_delete=models.CASCADE,db_column='ontology') #Ссылка на онтологию, к которой относится ограничение

    object_source = models.CharField(max_length=100, blank=False, unique=False, db_column='object_source') # Первый объект
    object_property = models.CharField(max_length=100, blank=False, unique=False, db_column='object_property') # Свойство    
    object_destanation = models.CharField(max_length=100, blank=False, unique=False,db_column='object_destanation') # Второй объект
    
    data = models.DateTimeField(db_column='data') #Дата создания онтологии
    
    def __str__(self):
        return "ontology:{} triplet:{}-{}->{}".format(self.ontology, self.object_source, self.object_property, self.object_destanation)
    

class RoleRestrictions(models.Model): #Ораничение для концепт свойство концепт
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_column='author') #Автор ограничения
    ontology = models.ForeignKey(CreatedOntology, on_delete=models.CASCADE, db_column='ontology') #Ссылка на онтологию, к которой относится ограничение

    first_concept = models.CharField(max_length=100, blank=False, unique=False, db_column='first_concept') # Первый концепт в ограничение
    first_role_second = models.CharField(max_length=100, blank=False, unique=False, db_column='first_role_second') # Роль    
    second_concept = models.CharField(max_length=100, blank=False, unique=False, db_column='second_concept') # Второй концепт в ограничение
    
    data = models.DateTimeField(db_column='data') #Дата создания онтологии

    def __str__(self):
        return "ontology:{} Role: {}-{}->{}".format(self.ontology, self.first_concept, self.first_role_second, self.second_concept)
    

class SimpleRulesForOntology(models.Model): #Задание простого правила транзитивности
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,db_column='author') #Автор записи
    ontology = models.ForeignKey(CreatedOntology, on_delete=models.CASCADE,db_column='ontology') #Ссылка на онтологию, к которой относится запись

    first_concept = models.CharField(max_length=100, blank=False, unique=False,db_column='first_concept') # Первый концепт в правиле
    first_role_second = models.CharField(max_length=100, blank=False, unique=False,db_column='first_role_second') # Роль    
    second_concept = models.CharField(max_length=100, blank=False, unique=False,db_column='second_concept') # Второй концепт в правиле
    second_role_third = models.CharField(max_length=100, blank=False, unique=False,db_column='second_role_third') # Роль
    third_concept = models.CharField(max_length=100, blank=False, unique=False,db_column='third_concept') # Третий концепт в правиле

    transitive_node = models.CharField(max_length=100, blank=False, unique=False,db_column='transitive_node') #соединяющий узел

    data = models.DateTimeField(db_column='data') # Дата создания правила

    def __str__(self):
        return "ontology:{} Rules: {}-{}->{}-{}->{}".format(self.ontology, self.first_concept, self.first_role_second, self.second_concept, self.second_role_third, self.third_concept)
    

##############################################################################################################################################
#################################                   МОДЕЛЬ ПОЛЬЗОВАТЕЛЯ                 ######################################################
##############################################################################################################################################


from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)




class MyUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            date_of_birth=date_of_birth,
            
        )
        
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    date_of_birth = models.DateField()
    avatar = models.ImageField(upload_to="user_photo",blank = True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin






    
    


    
    

ontology/app1/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from .forms import UploadFileForm
from django.conf import settings
import os
from app1.models import *
from owlready2 import *
import rdflib
from django.conf import settings
from datetime import datetime
import json



from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
# Create your views here.

def handle_uploaded_file(f):
    
    with open('ontology/app1/ontology_file/name.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


#####################################################################################################################
###########################################     INDEX PAGE        ###################################################
#####################################################################################################################

class IndexPage(View):
    def get(self, request):
        form = UploadFileForm()
        return render(request, 'app1/index.html', {'form': form},)
    def post(self, request):
        print("post:",request.POST)
        """
        path_ontology_absolute_path = os.path.join(settings.PATH_TO_ONTOLOGE_FILES, request.POST[""]) #Создания пути для сохранения онтологии
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponse('Good Load')
        else: 
            return HttpResponse('Bad load')
        """


#####################################################################################################################
###########################################     РЕДАКТОР ОНТОЛОГИЙ      #############################################
#####################################################################################################################

   

def addClass(mail, ontology, classname,subclassname): #Добавление класса
    objectAuthor = get_object_or_404(MyUser, email = mail) #получение объекта автора
    objectOntology = get_object_or_404(CreatedOntology, name = ontology) #получение объекта онтологии
    new_triplets = Triplets(author=objectAuthor, ontology=objectOntology, object_source= "http://www.semanticweb.org/valsosuke/ontologies/2020/9/untitled-ontology-18#" + subclassname, object_property= "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", object_destanation= "http://www.w3.org/2002/07/owl#Class", data = datetime.now())
    new_triplets.save()
    return True
    

def addSubClass(mail, ontology, classname, subclassname): #Добавление подкласса
    objectAuthor = get_object_or_404(MyUser, email = mail) #получение объекта автора
    objectOntology = get_object_or_404(CreatedOntology, name = ontology) #получение объекта онтологии
    new_triplets = Triplets(author=objectAuthor, ontology=objectOntology, object_source= "http://www.semanticweb.org/valsosuke/ontologies/2020/9/untitled-ontology-18#" + subclassname, object_property= "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", object_destanation= "http://www.w3.org/2002/07/owl#Class", data = datetime.now())
    
    new_triplets.save()
    new_triplets = Triplets(author=objectAuthor, ontology=objectOntology, object_source= "http://www.semanticweb.org/valsosuke/ontologies/2020/9/untitled-ontology-18#" + subclassname, object_property= "http://www.w3.org/2000/01/rdf-schema#subClassOf", object_destanation= "http://www.semanticweb.org/valsosuke/ontologies/2020/9/untitled-ontology-18#" + classname, data = datetime.now())
    new_triplets.save()
    return True
        

def addProperty(mail, ontology, propertyname,subpropertyname): #Добавление свойства
    objectAuthor = get_object_or_404(MyUser, email = mail) #получение объекта автора
    objectOntology = get_object_or_404(CreatedOntology, name = ontology) #получение объекта онтологии
    new_triplets = Triplets(author=objectAuthor, ontology=objectOntology, object_source= "http://www.semanticweb.org/valsosuke/ontologies/2020/9/untitled-ontology-18#" + subpropertyname, object_property= "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", object_destanation= "http://www.w3.org/2002/07/owl#ObjectProperty", data = datetime.now())
    new_triplets.save()
    return True
    

def addSubProperty(mail, ontology, propertyname, subpropertyname): #Добавление подсвойства
    objectAuthor = get_object_or_404(MyUser, email = mail) #получение объекта автора
    objectOntology = get_object_or_404(CreatedOntology, name = ontology) #получение объекта онтологии
    new_triplets = Triplets(author=objectAuthor, ontology=objectOntology, object_source= "http://www.semanticweb.org/valsosuke/ontologies/2020/9/untitled-ontology-18#" + subpropertyname, object_property= "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", object_destanation= "http://www.w3.org/2002/07/owl#ObjectProperty", data = datetime.now())
    
    new_triplets.save()
    new_triplets = Triplets(author=objectAuthor, ontology=objectOntology, object_source= "http://www.semanticweb.org/valsosuke/ontologies/2020/9/untitled-ontology-18#" + subpropertyname, object_property= "http://www.w3.org/2000/01/rdf-schema#subPropertyOf", object_destanation= "http://www.semanticweb.org/valsosuke/ontologies/2020/9/untitled-ontology-18#" + propertyname, data = datetime.now())
    new_triplets.save()
    return True


def getAllClasses(): #Получение всех элементов, имеющих тип класс
    allClasses = list(Triplets.objects.filter(object_property="http://www.w3.org/1999/02/22-rdf-syntax-ns#type", object_destanation="http://www.w3.org/2002/07/owl#Class").values_list('object_source', flat=True))
    if (len(allClasses)):
       allClasses = [i.split("#")[1] for i in allClasses]
    allClasses.insert(0,"#")
     #Добавление корневого элемента
    return allClasses

def getAllProperty(): #Получение всех элементов, имеющих тип свойство
    allProperty = list(Triplets.objects.filter(object_property="http://www.w3.org/1999/02/22-rdf-syntax-ns#type", object_destanation="http://www.w3.org/2002/07/owl#http://www.w3.org/2002/07/owl#Object#Property").values_list('object_source', flat=True))
    if (len(allProperty)):
       allProperty = [i.split("#")[1] for i in allProperty]
    allProperty.insert(0,"#")
     #Добавление корневого элемента
    return allProperty

class OntologyCreationEnvironment(View): #Отдается начальная страница
    def get(self, request):

        return render(request, 'app1/creation_enviroment_ontology.html', {"listOfClasses": getAllClasses()})

@method_decorator(csrf_exempt, name='dispatch')
class PostHandler(View):   
    def post(self, request): #Здесь обрабатываются события добавления, удаления класса, добавления, удаления событися ...
        print(request.POST)
        if request.user.is_authenticated:
            mail = request.user.email

            ##########################          Работа с классами              ##########################################

            if(request.POST.get("action")=="addClass" and request.POST.get("classname") == "#"): # Если добавление класса
                if(addClass(mail = mail, ontology= request.POST.get("ontology"), classname = request.POST.get("classname"),subclassname=request.POST.get("subclassname"))):
                    HttpResponse(status=200)
                else:
                    HttpResponse(status=404)

            if(request.POST.get("action")=="addSubClass" and request.POST.get("classname") != "#"): #Если добавление подкласса
                if(addSubClass(mail = mail, ontology= request.POST.get("ontology"),classname = request.POST.get("classname"), subclassname=request.POST.get("subclassname"))):
                    HttpResponse(status=200)
                else:
                    HttpResponse(status=404)
            #########################          Работа со свойствами            ##########################################
            
            if(request.POST.get("action")=="addProperty" and request.POST.get("proprtyname") == "#"): # Если добавление класса
                if(addProperty(mail = mail, ontology= request.POST.get("ontology"), propertyname = request.POST.get("propertyname"),subpropertyname=request.POST.get("subpropertyname"))):
                    HttpResponse(status=200)
                else:
                    HttpResponse(status=404)

            if(request.POST.get("action")=="addSubProperty" and request.POST.get("protpertyname") != "#"): #Если добавление подкласса
                if(addSubProperty(mail = mail, ontology= request.POST.get("ontology"),classname = request.POST.get("propertyname"), subpropertyname=request.POST.get("subproperyname"))):
                    HttpResponse(status=200)
                else:
                    HttpResponse(status=404)
            
            #########################          Работа с экземплярами            ##########################################

        return HttpResponse("hello")

def getStructure(action):
    if(action == "Class"):
        allClasses = getAllClasses() #Получение списка всех элементов, имеющих тип класс
        allSubClasses = list(Triplets.objects.filter(object_property="http://www.w3.org/2000/01/rdf-schema#subClassOf").values_list('object_source', flat=True))
        allSubClasses = [i.split('#')[1] for i in allSubClasses]
        principals = list(set(allClasses).symmetric_difference(allSubClasses)) #Список принципов
        principals.remove('#') #Удаление корневого элемента
        print("principals",principals)

        treeClassList = [] #Возвращаемое дерево классов в виде list
        
        for i in principals: #Добавление принциполов в список словарей
            treeClassList.append({'name': i, 'parent':'#'})
        

ontology/app1/templates/app1/creation_enviroment_ontology.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" type="image/png" href="{% static "app1/images/favicon-32x32.png" %}" sizes="32x32" />
  <link rel="icon" type="image/png" href="{% static "app1/images/favicon-16x16.png" %}" sizes="16x16" />
  <title>Ontology</title>
  <!--stylesheet-->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,900" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="{% static "app1/styles/styles.css" %}" rel="stylesheet" type="text/css">
  <link href="{% static "app1/styles/custom-responsive-styles.css" %}" rel="stylesheet" type="text/css">
   <link href="{% static "app1/styles/tree_view.css" %}" rel="stylesheet" type="text/css">
  <!--scripts-->
  <script type="text/javascript" src="{% static "app1/scripts/jquery-3.2.1.min.js" %}"></script>
  <script type="text/javascript" src="{% static "app1/scripts/all-plugins.js" %}"></script>
  <script type="text/javascript" src="{% static "app1/scripts/plugins-activate.js" %}"></script>
  <script type="text/javascript" src="{% static "app1/js/bootstrap-filestyle.min.js" %}"> </script>
  <script type="text/javascript" src="{% static "app1/scripts/ontology_creation_enviroment_post_handler.js" %}"> </script>

  

</head>

<body id="page-top" onload="loadStructureClass(); loadStructureProperty()">
  <!-- Navigation -->
  <div class="logo">
    <i class="fa fa-plane" aria-hidden="true"><span>Имя пользователя</span></i>
  </div>
  <a class="menu-toggle rounded" href="#">
    <i class="fa fa-bars"></i>
  </a>
  <nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a class="smooth-scroll" href="#Header"></a>
      </li>
      <li class="sidebar-nav-item">
        <a class="smooth-scroll" href="#page-top">Дом</a>
      </li>
      
      <!--
      <li class="sidebar-nav-item">
        <a class="smooth-scroll" href="#Services">Services</a>
      </li>
      
      <li class="sidebar-nav-item">
        <a class="smooth-scroll" href="#Portfolio">Portfolio</a>
      </li>-->
      <li class="sidebar-nav-item">
        <a class="smooth-scroll" href="#Classes">Классы</a>
      </li>
      <li class="sidebar-nav-item">
        <a class="smooth-scroll" href="#ObjectPropertys">Свойства</a>
      </li>
      <li class="sidebar-nav-item">
        <a class="smooth-scroll" href="#Individuals">Экземпляры</a>
      </li>

      

      <!--<li class="sidebar-nav-item">
        <a class="smooth-scroll" href="#Contact">Contact</a>
      </li>-->
    </ul>
  </nav>
  <!-- Header Starts -->
  <section id="Banner" class="content-section" >
    <div class="container content-wrap text-center">
      <h1>Редактор онтологии</h1>
      <h3>
          <em>Всем привет, тут можно редактировать онтологии</em>
        </h3>
    </div>
    <div class="overlay"></div>
  </section>

  <!-- -----------------------------CLASSES SECTION--------------------------------------------------------------- -->
  <section id="Classes" class="content-section" >
    <div class="container content-wrap text-center">
      <h1>Классы</h1>
    </div>
    <div id="anotherSpan" class="container content-wrap text-left"> <!-- этот div для раскрытия списка классов -->
        <ul class="tree" id="tree">
        <!--<li name="Животные">Животные
          <ul>
            <li name="Млекопитающие">Млекопитающие
              <ul>
                <li>Коровы</li>
                <li>Ослы</li>
                <li>Собаки</li>
                <li>Тигры</li>
              </ul>
            </li>
            <li>Другие
              <ul>
                <li>Змеи</li>
                <li>Птицы</li>
                <li>Ящерицы</li>
              </ul>
            </li>
          </ul>
        </li>
        <li>Рыбы
          <ul>
            <li>Аквариумные
              <ul>
                <li>Гуппи</li>
                <li>Скалярии</li>
              </ul>
            </li>
            <li>Морские
              <ul>
                <li>Морская форель</li>
              </ul>
            </li>
          </ul>
        </li>-->
      </ul>
    </div>
    <div>
      <input id="subClassName" name="subClassName" type="text">
      <select id="className" name = "className">
        {% for i in listOfClasses %}
          <option id="{{i}}" name="{{i}}">{{i}}</option>
        {%  endfor  %}
      </select>
      
      {% csrf_token %}
      <button onclick="addClass(this)">Добавить класс</button>
    </div>
    <div class="overlay"></div>
  </section>
  <!- ------------------------------ END CLASSES SECTION---------------------------------------------------------------- ->

  <!-- -----------------------------     PROPERTY SECTION            --------------------------------------------------------------- -->
  <section id="Properties" class="content-section" >
    <div class="container content-wrap text-center">
      <h1>Свойства</h1>
    </div>
    <div id="anotherSpan" class="container content-wrap text-left"> <!-- этот div для раскрытия списка Свойств -->
        <ul class="treeProperty" id="treeProperty">
        
        </ul>
    </div>
    <div>
      <input id="subPropertyName" name="subPropertyName" type="text">
      <select id="propertyName" name = "propertyName">
        {% for i in listOfProperies %}
          <option id="{{i}}" name="{{i}}">{{i}}</option>
        {%  endfor  %}
      </select>
      
      {% csrf_token %}
      <button onclick="addProperty(this)">Добавить класс</button>
    </div>
    <div class="overlay"></div>
  </section>
  <!- ------------------------------ END PROPERTY SECTION---------------------------------------------------------------- ->


  
  <section id="Contact" class="content-section">
    <div class="container">
      <div class="block-heading">
        <h2>Загрузка онтологии</h2>
      </div>
      <div class="row">
        
        <div class="col-sm-12 col-md-6 col-lg-6">
          <div class="form-wrap">
            <form method="post">{% csrf_token %}
              <div class="fname floating-label">
                <!--<input type="text" class="floating-input" name="full name" />-->
                {{ form.name }}
                <label for="id_name">Название онтологии</label>
              </div>
              <div class="company floating-label">
                <!--<textarea type="text" class="floating-input" name="company" /></textarea>-->
                {{form.description}}
                <label for="id_description">Описание онтологии</label>
              </div>
              <div class="fname floating-label">
                <label for="file" class="btn" style="background-color: pink; color: #000000">Открыть расположение</label>
                {{ form.file }}
              </div>
              <div class="submit-btn">
                <button type="submit">Загрузка</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  
  <footer class="footer text-center">
    <div class="container">
      <ul class="list-inline">
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white mr-3" href="javascript:void(0)">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
        </li>
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white mr-3" href="javascript:void(0)">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
        </li>
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white" href="javascript:void(0)">
              <i class="fa fa-linkedin" aria-hidden="true"></i>
            </a>
        </li>
      </ul>
      <p class="text-muted small mb-0">Copyright © 2020</p>
      <p class="text-muted small mb-0">Designed by <a href="#" target="_balnk">Валерон</p>
    </div>
  </footer>
 
</body>

</html>

ontology/app1/templates/app1/upload.html
<!DOCTYPE>
<head></head>
<body>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
</body>